source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-remote-theme"
  gem "jekyll-seo-tag"
end

# Windows and JRuby support
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo"
  gem "tzinfo-data"
end

# Performance and compatibility gems
gem "wdm", :platforms => [:mingw, :x64_mingw, :mswin]
gem "http_parser.rb", :platforms => [:jruby]
gem "webrick"